import js from "@eslint/js";
import { defineConfig } from "eslint/config";

export default defineConfig([
  {
    ignores: ["foundry/**", "dist/**"],
  },
  js.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        game: "readonly",
        ui: "readonly",
        canvas: "readonly",
        Actor: "readonly",
        Item: "readonly",
        ChatMessage: "readonly",
        Macro: "readonly",
        User: "readonly",
        Scene: "readonly",
        Combat: "readonly",
        Combatant: "readonly",
        Folder: "readonly",
        Roll: "readonly",
        Hooks: "readonly",
        Handlebars: "readonly",
        CONFIG: "readonly",
        AudioHelper: "readonly",
        Dialog: "readonly",
        FormApplication: "readonly",
        Application: "readonly",
        FilePicker: "readonly",
        mergeObject: "readonly",
        duplicate: "readonly",
        foundry: "readonly",
        CONST: "readonly",
        renderTemplate: "readonly",
        getProperty: "readonly",
        setProperty: "readonly",
        expandObject: "readonly",
        isNewerVersion: "readonly",
        isObjectEmpty: "readonly",
        TextEditor: "readonly",
        randomID: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        getDocumentClass: "readonly",
        SortingHelpers: "readonly",
        fromUuid: "readonly"
      },
    },
    rules: {
      "no-console": "off",
      "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
    },
  },
]);
