import SYNTHICIDE from "../helpers/config.mjs";
/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class SynthicideActor extends Actor {

  /** @override */
  async _preUpdate(changed, options, user) {
    const allowed = await super._preUpdate(changed, options, user);
    if (allowed === false) return false;
    return allowed;
  }

  /**
   * @override
   */
  prepareDerivedData() {
    super.prepareDerivedData();
    // Only calculate derived data here; aggregation is triggered by item changes
    // Derived data for sharper actors is now handled in the data model.
    // ...existing code for other derived data...
  }

  /**
   * Aggregate all item modifiers and apply to this actor.
   *
   * This method sums up all attribute and non-attribute modifiers from the actor's owned items,
   * applies the aggregated attribute modifiers to the actor's attributes (persisting .modifier if changed),
   * recalculates .current in memory, and applies non-attribute modifiers to arbitrary system paths.
   *
   * This should be called from item data model hooks (e.g., _onCreate, _onUpdate, _onDelete) when item changes
   * may affect actor attributes or other system data.
   *
   * @async
   * @param {Object} [options] - Options for aggregation.
   * @param {boolean} [options.debug=false] - If true, collects and outputs debug information about modifier aggregation.
   * @returns {Promise<void>} Resolves when aggregation and updates are complete.
   */
  async aggregateAndApplyItemModifiers({ debug = false } = {}) {
    const attributeKeys = Object.keys(SYNTHICIDE.attributes);
    let debugItemContrib = [];
    const attributeModifiers = Object.fromEntries(attributeKeys.map(key => [key, 0]));
    const nonAttributeModifiers = [];
    for (const item of this.items) {
      const dataModel = item?.system;
      if (!dataModel?.aggregateAttributeModifiers) continue;
      const debugArr = debug ? [] : undefined;
      const { attributeModifiers: itemAttrMods, nonAttributeModifiers: itemNonAttrMods } = dataModel.aggregateAttributeModifiers(attributeKeys);
      for (const key of attributeKeys) {
        attributeModifiers[key] += Number(itemAttrMods[key] ?? 0);
      }
      if (Array.isArray(itemNonAttrMods)) nonAttributeModifiers.push(...itemNonAttrMods);
      if (debugArr && debugArr.length) debugItemContrib.push(...debugArr);
    }
    // Prepare update object for changed modifiers/current
    const updatedAttributes = {};
    for (const key of attributeKeys) {
      if (!this.system?.attributes?.[key]) continue;
      const newModifier = Number(attributeModifiers[key] ?? 0);
      const oldModifier = Number(this.system.attributes[key].modifier ?? 0);
      if (oldModifier !== newModifier) {
        updatedAttributes[key] = {
          ...this.system.attributes[key],
          modifier: newModifier
        };
      }
    }
    if (Object.keys(updatedAttributes).length > 0) {
      await this.update({ "system.attributes": updatedAttributes });
    }
    // Always recalculate current in memory after aggregation
    for (const key of attributeKeys) {
      if (!this.system?.attributes?.[key]) continue;
      this.system.attributes[key].current =
        this.system.attributes[key].base +
        this.system.attributes[key].modifier +
        this.system.attributes[key].increase;
    }
    if (debug) {
      this.debugModifierAggregation(attributeKeys, attributeModifiers, debugItemContrib);
    }
    this.applyNonAttributeModifiers(nonAttributeModifiers);
  }

  /**
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
   * Output debug information for modifier aggregation.
   * @param {Array<string>} attributeKeys - The list of attribute keys.
   * @param {Object} attributeModifiers - The aggregated attribute modifiers.
   * @param {Array<Object>} debugItemContrib - The debug info array.
   */
  debugModifierAggregation(attributeKeys, attributeModifiers, debugItemContrib) {
    console.groupCollapsed(`[Synthicide] Modifier aggregation: ${this.name}`);
    console.table(
      attributeKeys.map((key) => ({
        attribute: key,
        preparedModifier: Number(
          this.system?.attributes?.[key]?.modifier - Number(attributeModifiers[key] ?? 0)
        ),
        aggregatedDelta: Number(attributeModifiers[key] ?? 0),
        finalModifier: Number(this.system?.attributes?.[key]?.modifier ?? 0),
        current: Number(this.system?.attributes?.[key]?.current ?? 0),
      }))
    );
    if (debugItemContrib.length) console.table(debugItemContrib);
    console.groupEnd();
  }

  /**
   * Apply non-attribute modifiers to any system path on the actor.
   * @param {Array<Object>} nonAttributeModifiers - The non-attribute modifiers to apply.
   */
  applyNonAttributeModifiers(nonAttributeModifiers) {
    for (const mod of nonAttributeModifiers) {
      if (!mod.target) continue;
      let path = mod.target;
      if (!path.startsWith('system.')) path = `system.${path}`;
      let current = foundry.utils.getProperty(this, path);
      if (current === undefined) current = 0;
      let newValue = current;
      if (mod.type === 'set') {
        newValue = mod.value;
      } else if (mod.type === 'penalty') {
        newValue -= mod.value ?? 0;
      } else {
        newValue += mod.value ?? 0;
      }
      foundry.utils.setProperty(this, path, newValue);
    }
  }
  
}
