import SYNTHICIDE from "../helpers/config.mjs";
/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class SynthicideActor extends Actor {

  /** @override */
  async _preUpdate(changed, options, user) {
    const allowed = await super._preUpdate(changed, options, user);
    if (allowed === false) return false;
    return allowed;
  }

  /**
   * @override
   */
  prepareDerivedData() {
    super.prepareDerivedData();
    // Only calculate derived data here; aggregation is triggered by item changes
    // Derived data for sharper actors is now handled in the data model.
    // ...existing code for other derived data...
  }

  /**
   * Aggregate all item modifiers and apply to this actor.
   *
   * This method sums up all attribute and non-attribute modifiers from the actor's owned items,
   * applies the aggregated attribute modifiers to the actor's attributes (persisting .modifier if changed),
   * recalculates .current in memory, and applies non-attribute modifiers to arbitrary system paths.
   *
   * This should be called from item data model hooks (e.g., _onCreate, _onUpdate, _onDelete) when item changes
   * may affect actor attributes or other system data.
   *
   * @async
   * @param {Object} [options] - Options for aggregation.
   * @param {boolean} [options.debug=false] - If true, collects and outputs debug information about modifier aggregation.
   * @returns {Promise<void>} Resolves when aggregation and updates are complete.
   */
  async aggregateAndApplyItemModifiers({ debug = false, render = true } = {}) {
    const attributeKeys = Object.keys(SYNTHICIDE.attributes);
    const attributeModifiers = Object.fromEntries(attributeKeys.map(key => [key, 0]));
    const nonAttributeModifiers = [];
    let debugItemContrib = [];

    for (const item of this.items) {
      const { system: dataModel } = item || {};
      if (typeof dataModel?.aggregateAttributeModifiers !== "function") continue;
      const debugArr = debug ? [] : undefined;
      const { attributeModifiers: itemAttrMods, nonAttributeModifiers: itemNonAttrMods } =
        dataModel.aggregateAttributeModifiers(attributeKeys, debugArr);

      for (const [key, val] of Object.entries(itemAttrMods)) {
        attributeModifiers[key] += Number(val ?? 0);
      }
      if (Array.isArray(itemNonAttrMods)) nonAttributeModifiers.push(...itemNonAttrMods);
      if (debugArr && debugArr.length) debugItemContrib.push(...debugArr);
    }

    // Persist any modifier values that changed
    // so Foundry merges individual fields rather than replacing the whole attributes object.
    const updates = {};
    for (const key of attributeKeys) {
      const attr = this.system?.attributes?.[key];
      if (!attr) continue;
      const newModifier = Number(attributeModifiers[key] ?? 0);
      if (Number(attr.modifier ?? 0) !== newModifier) {
        updates[`system.attributes.${key}.modifier`] = newModifier;
      }
    }
    Object.assign(updates, this.buildNonAttributeModifierUpdates(nonAttributeModifiers));
    if (Object.keys(updates).length > 0) {
      await this.update(updates, { render });
    }

    // Always recalculate current in memory after aggregation
    for (const key of attributeKeys) {
      const attr = this.system?.attributes?.[key];
      if (!attr) continue;
      attr.current = attr.base + attr.modifier + attr.increase;
    }
    if (debug) {
      this.debugModifierAggregation(attributeKeys, attributeModifiers, debugItemContrib);
    }
  }

  /**
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
   * Output debug information for modifier aggregation.
   * @param {Array<string>} attributeKeys - The list of attribute keys.
   * @param {Object} attributeModifiers - The aggregated attribute modifiers.
   * @param {Array<Object>} debugItemContrib - The debug info array.
   */
  debugModifierAggregation(attributeKeys, attributeModifiers, debugItemContrib) {
    console.groupCollapsed(`[Synthicide] Modifier aggregation: ${this.name}`);
    console.table(
      attributeKeys.map((key) => ({
        attribute: key,
        preparedModifier: Number(
          this.system?.attributes?.[key]?.modifier - Number(attributeModifiers[key] ?? 0)
        ),
        aggregatedDelta: Number(attributeModifiers[key] ?? 0),
        finalModifier: Number(this.system?.attributes?.[key]?.modifier ?? 0),
        current: Number(this.system?.attributes?.[key]?.current ?? 0),
      }))
    );
    if (debugItemContrib.length) console.table(debugItemContrib);
    console.groupEnd();
  }

  /**
   * Build update payload for non-attribute modifiers.
   * @param {Array<Object>} nonAttributeModifiers - The non-attribute modifiers to apply.
   * @returns {Object} flat update payload compatible with Actor.update
   */
  buildNonAttributeModifierUpdates(nonAttributeModifiers) {
    const updates = {};
    for (const mod of nonAttributeModifiers) {
      if (!mod.target) continue;
      let path = mod.target;
      if (!path.startsWith('system.')) path = `system.${path}`;

      const stagedValue = updates[path];
      let current = stagedValue;
      if (current === undefined) current = foundry.utils.getProperty(this, path);
      if (current === undefined) current = 0;

      const numericCurrent = Number(current);
      const baseValue = Number.isFinite(numericCurrent) ? numericCurrent : 0;
      const numericModValue = Number(mod.value ?? 0);

      const newValue = mod.type === 'set'
        ? mod.value
        : mod.type === 'penalty'
          ? baseValue - numericModValue
          : baseValue + numericModValue;

      updates[path] = newValue;
    }
    return updates;
  }

  async damageActor(damage) {
    if (!damage || !["sharper", "npc"].includes(this.type)) return;
    const updates = {};
    let damageRemaining = damage;
    // Check force barrier first and apply damage to it
    if (this.system.forceBarrier.value > 0) {
      const barrierAmount = Math.min(this.system.forceBarrier.value, damageRemaining);
      if (barrierAmount > 0) {
        damageRemaining -= barrierAmount;
        updates['system.forceBarrier.value'] = Math.max(this.system.forceBarrier.value - barrierAmount, 0);
      }
    }

    // Apply any leftover to hitPoints
    if (damageRemaining > 0) {
      const hitPointsAmount = Math.min(this.system.hitPoints.value, damageRemaining);
      if (hitPointsAmount > 0) {
        updates['system.hitPoints.value'] = Math.max(this.system.hitPoints.value - hitPointsAmount, 0);
      }
    }

    await this.update(updates);
  }

  async healActor(healing) {
    if (!healing || !["sharper", "npc"].includes(this.type)) return;
    const updates = {};
    updates['system.hitPoints.value'] = Math.min(this.system.hitPoints.value + healing, this.system.hitPoints.max);
    await this.update(updates);
  }
}
