import SYNTHICIDE from "../helpers/config.mjs";
/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class SynthicideActor extends Actor {

  /** @override */
  async _preUpdate(changed, options, user) {
    const allowed = await super._preUpdate(changed, options, user);
    if (allowed === false) return false;
    return allowed;
  }

  /**
   * @override
   */
  prepareDerivedData() {
    super.prepareDerivedData();
    const debugModifiers = Boolean(SYNTHICIDE.debug?.synthicideModifiers);

    const attributeKeys = Object.keys(SYNTHICIDE.attributes);
    const debugItemContrib = [];
    const { attributeModifiers, nonAttributeModifiers } = this.aggregateAttributeModifiers(this.items, attributeKeys, debugItemContrib, debugModifiers);

    this.applyAttributeModifiers(attributeKeys, attributeModifiers);

    if (debugModifiers) {
      this.debugModifierAggregation(attributeKeys, attributeModifiers, debugItemContrib);
    }

    // --- 3. Calculate derived data (base class or your own logic) ---
    if (this.type === "sharper") {
      this.system.foodDays.min = -(6 + (this.system.attributes.toughness.current ?? 0));
    }

    this.applyNonAttributeModifiers(nonAttributeModifiers);
  }

  /**
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  // --- Helper functions for prepareDerivedData ---
  /**
   * Aggregate attribute and non-attribute modifiers from items.
   * @param {Array} items - The items to aggregate modifiers from.
   * @param {Array<string>} attributeKeys - The list of attribute keys.
   * @param {Array<Object>} debugItemContrib - Array to collect debug info.
   * @param {boolean} debugModifiers - Whether to collect debug info.
   * @returns {{ attributeModifiers: Object, nonAttributeModifiers: Array }}
   */
  aggregateAttributeModifiers(items, attributeKeys, debugItemContrib, debugModifiers) {
    const attributeModifiers = Object.fromEntries(attributeKeys.map(key => [key, 0]));
    const nonAttributeModifiers = [];
    for (const item of items) {
      if (!Array.isArray(item.system?.modifiers)) continue;
      for (const mod of item.system.modifiers) {
        if (!mod || !mod.target) continue;
        const normalizedTarget = String(mod.target).replace(/^system\./, '');
        const attrKey = normalizedTarget.replace(/^attributes\./, '');
        if (attributeKeys.includes(attrKey)) {
          const modValue = Number(mod.value ?? 0);
          if (mod.type === 'set') attributeModifiers[attrKey] = modValue;
          else if (mod.type === 'penalty') attributeModifiers[attrKey] -= modValue;
          else attributeModifiers[attrKey] += modValue;
          if (debugModifiers) debugItemContrib.push({ item: item.name, target: attrKey, type: mod.type ?? 'bonus', value: modValue, running: attributeModifiers[attrKey] });
        } else {
          nonAttributeModifiers.push(mod);
        }
      }
    }
    return { attributeModifiers, nonAttributeModifiers };
  }

  /**
   * Apply aggregated attribute modifiers to the actor's system attributes.
   * @param {Array<string>} attributeKeys - The list of attribute keys.
   * @param {Object} attributeModifiers - The aggregated attribute modifiers.
   */
  applyAttributeModifiers(attributeKeys, attributeModifiers) {
    for (const key of attributeKeys) {
      if (!this.system?.attributes?.[key]) continue;
      const existingModifier = Number(this.system.attributes[key].modifier ?? 0);
      this.system.attributes[key].modifier = existingModifier + Number(attributeModifiers[key] ?? 0);
      this.system.attributes[key].current =
        this.system.attributes[key].base +
        this.system.attributes[key].modifier +
        this.system.attributes[key].increase;
    }
  }

  /**
   * Output debug information for modifier aggregation.
   * @param {Array<string>} attributeKeys - The list of attribute keys.
   * @param {Object} attributeModifiers - The aggregated attribute modifiers.
   * @param {Array<Object>} debugItemContrib - The debug info array.
   */
  debugModifierAggregation(attributeKeys, attributeModifiers, debugItemContrib) {
    console.groupCollapsed(`[Synthicide] Modifier aggregation: ${this.name}`);
    console.table(
      attributeKeys.map((key) => ({
        attribute: key,
        preparedModifier: Number(
          this.system?.attributes?.[key]?.modifier - Number(attributeModifiers[key] ?? 0)
        ),
        aggregatedDelta: Number(attributeModifiers[key] ?? 0),
        finalModifier: Number(this.system?.attributes?.[key]?.modifier ?? 0),
        current: Number(this.system?.attributes?.[key]?.current ?? 0),
      }))
    );
    if (debugItemContrib.length) console.table(debugItemContrib);
    console.groupEnd();
  }

  /**
   * Apply non-attribute modifiers to any system path on the actor.
   * @param {Array<Object>} nonAttributeModifiers - The non-attribute modifiers to apply.
   */
  applyNonAttributeModifiers(nonAttributeModifiers) {
    for (const mod of nonAttributeModifiers) {
      if (!mod.target) continue;
      let path = mod.target;
      if (!path.startsWith('system.')) path = `system.${path}`;
      let current = foundry.utils.getProperty(this, path);
      if (current === undefined) current = 0;
      let newValue = current;
      if (mod.type === 'set') {
        newValue = mod.value;
      } else if (mod.type === 'penalty') {
        newValue -= mod.value ?? 0;
      } else {
        newValue += mod.value ?? 0;
      }
      foundry.utils.setProperty(this, path, newValue);
    }
  }

  
}
